-- ============================================================================
-- شركاؤنا — Seed all 6 partner pages with real content from /Our partners/*.html
--
-- NON-DESTRUCTIVE: UPDATE existing rows + INSERT missing rows.
-- No DELETE, TRUNCATE, or DROP. Safe to run multiple times.
-- ============================================================================

DO $$
DECLARE
  v_pid UUID;
BEGIN
  ----------------------------------------------------------------------------
  -- 1. LeFouilleurma
  ----------------------------------------------------------------------------
  SELECT id INTO v_pid FROM pages WHERE slug = '/partners/lefouilleurma' LIMIT 1;
  IF v_pid IS NULL THEN
    INSERT INTO pages (title, slug, status) VALUES ('LeFouilleurma', '/partners/lefouilleurma', 'published') RETURNING id INTO v_pid;
  END IF;
  -- Section 1 — Hero
  UPDATE page_sections SET section_type = 'hero', content = '{"heading":"LeFouilleurma","subheading":"شريك وطني","description":"شريك وطني للجمعية المغربية لهواة البحث والاستكشاف، متخصص في بيع وشراء أجهزة الكشف عن المعادن والكنوز على المستوى الوطني.","backgroundImage":"","buttons":[{"id":"btn-pr-website","label":"زيارة الموقع الإلكتروني","url":"#","variant":"primary"},{"id":"btn-pr-contact","label":"تواصل مع الشريك","url":"#prForm","variant":"secondary"}]}'::jsonb, settings='{}'::jsonb, styles='{}'::jsonb WHERE page_id = v_pid AND sort_order = 1;
  IF NOT FOUND THEN INSERT INTO page_sections (id, page_id, section_type, visible, sort_order, content, settings, styles) VALUES (gen_random_uuid(), v_pid, 'hero', TRUE, 1, '{"heading":"LeFouilleurma","subheading":"شريك وطني","description":"شريك وطني للجمعية المغربية لهواة البحث والاستكشاف، متخصص في بيع وشراء أجهزة الكشف عن المعادن والكنوز على المستوى الوطني.","backgroundImage":"","buttons":[{"id":"btn-pr-website","label":"زيارة الموقع الإلكتروني","url":"#","variant":"primary"},{"id":"btn-pr-contact","label":"تواصل مع الشريك","url":"#prForm","variant":"secondary"}]}'::jsonb, '{}'::jsonb, '{}'::jsonb); END IF;
  -- Section 2 — About
  UPDATE page_sections SET section_type = 'custom', content = '{"_renderer":"partnerAbout","eyebrow":"عن LeFouilleurma","heading":"LeFouilleurma","paragraphs":["LeFouilleurma هي شركة مغربية متخصصة في بيع وشراء أجهزة الكشف عن المعادن والكنوز. تقدم الشركة مجموعة واسعة من الأجهزة المتطورة لتلبية احتياجات الهواة والمحترفين على حد سواء.","نعمل مع الجمعية المغربية لهواة البحث والاستكشاف في إطار شراكة وطنية تهدف إلى توفير أحدث أجهزة الكشف والتنقيب لأعضاء الجمعية بأسعار تفضيلية."]}'::jsonb, settings='{}'::jsonb, styles='{}'::jsonb WHERE page_id = v_pid AND sort_order = 2;
  IF NOT FOUND THEN INSERT INTO page_sections (id, page_id, section_type, visible, sort_order, content, settings, styles) VALUES (gen_random_uuid(), v_pid, 'custom', TRUE, 2, '{"_renderer":"partnerAbout","eyebrow":"عن LeFouilleurma","heading":"LeFouilleurma","paragraphs":["LeFouilleurma هي شركة مغربية متخصصة في بيع وشراء أجهزة الكشف عن المعادن والكنوز. تقدم الشركة مجموعة واسعة من الأجهزة المتطورة لتلبية احتياجات الهواة والمحترفين على حد سواء.","نعمل مع الجمعية المغربية لهواة البحث والاستكشاف في إطار شراكة وطنية تهدف إلى توفير أحدث أجهزة الكشف والتنقيب لأعضاء الجمعية بأسعار تفضيلية."]}'::jsonb, '{}'::jsonb, '{}'::jsonb); END IF;
  -- Section 3 — Contact
  UPDATE page_sections SET section_type = 'custom', content = '{"_renderer":"partnerContact","email":"contact@lefouilleurma.ma","phone":"+212 666 000 000","website":"www.lefouilleurma.ma","address":"شارع الزرقطوني، أكادير، المغرب"}'::jsonb, settings='{}'::jsonb, styles='{}'::jsonb WHERE page_id = v_pid AND sort_order = 3;
  IF NOT FOUND THEN INSERT INTO page_sections (id, page_id, section_type, visible, sort_order, content, settings, styles) VALUES (gen_random_uuid(), v_pid, 'custom', TRUE, 3, '{"_renderer":"partnerContact","email":"contact@lefouilleurma.ma","phone":"+212 666 000 000","website":"www.lefouilleurma.ma","address":"شارع الزرقطوني، أكادير، المغرب"}'::jsonb, '{}'::jsonb, '{}'::jsonb); END IF;
  -- Section 4 — CTA
  UPDATE page_sections SET section_type = 'custom', content = '{"_renderer":"partnerCta","heading":"هل أنت مستعد للشراكة معنا؟","description":"","buttonLabel":"تواصل معنا","buttonUrl":"#prForm"}'::jsonb, settings='{}'::jsonb, styles='{}'::jsonb WHERE page_id = v_pid AND sort_order = 4;
  IF NOT FOUND THEN INSERT INTO page_sections (id, page_id, section_type, visible, sort_order, content, settings, styles) VALUES (gen_random_uuid(), v_pid, 'custom', TRUE, 4, '{"_renderer":"partnerCta","heading":"هل أنت مستعد للشراكة معنا؟","description":"","buttonLabel":"تواصل معنا","buttonUrl":"#prForm"}'::jsonb, '{}'::jsonb, '{}'::jsonb); END IF;
  RAISE NOTICE 'LeFouilleurma seeded (% sections)', (SELECT COUNT(*) FROM page_sections WHERE page_id = v_pid);

  ----------------------------------------------------------------------------
  -- 2. SENOTEC
  ----------------------------------------------------------------------------
  SELECT id INTO v_pid FROM pages WHERE slug = '/partners/senotec' LIMIT 1;
  IF v_pid IS NULL THEN
    INSERT INTO pages (title, slug, status) VALUES ('SENOTEC', '/partners/senotec', 'published') RETURNING id INTO v_pid;
  END IF;
  UPDATE page_sections SET section_type = 'hero', content = '{"heading":"SENOTEC","subheading":"شريك دولي","description":"شريك دولي للجمعية المغربية لهواة البحث والاستكشاف، متخصص في الحلول التقنية والأمنية المتطورة على المستوى الدولي.","backgroundImage":"","buttons":[{"id":"btn-pr-website","label":"زيارة الموقع الإلكتروني","url":"#","variant":"primary"},{"id":"btn-pr-contact","label":"تواصل مع الشريك","url":"#prForm","variant":"secondary"}]}'::jsonb, settings='{}'::jsonb, styles='{}'::jsonb WHERE page_id = v_pid AND sort_order = 1;
  IF NOT FOUND THEN INSERT INTO page_sections (id, page_id, section_type, visible, sort_order, content, settings, styles) VALUES (gen_random_uuid(), v_pid, 'hero', TRUE, 1, '{"heading":"SENOTEC","subheading":"شريك دولي","description":"شريك دولي للجمعية المغربية لهواة البحث والاستكشاف، متخصص في الحلول التقنية والأمنية المتطورة على المستوى الدولي.","backgroundImage":"","buttons":[{"id":"btn-pr-website","label":"زيارة الموقع الإلكتروني","url":"#","variant":"primary"},{"id":"btn-pr-contact","label":"تواصل مع الشريك","url":"#prForm","variant":"secondary"}]}'::jsonb, '{}'::jsonb, '{}'::jsonb); END IF;
  UPDATE page_sections SET section_type = 'custom', content = '{"_renderer":"partnerAbout","eyebrow":"عن SENOTEC","heading":"SENOTEC","paragraphs":["SENOTEC هي شركة دولية متخصصة في تقديم الحلول التقنية والأمنية المتطورة. تمتلك الشركة خبرة واسعة في مجال أنظمة المراقبة والحماية الإلكترونية للمؤسسات والمنشآت.","نعمل مع الجمعية المغربية لهواة البحث والاستكشاف في إطار شراكة دولية تهدف إلى تعزيز الأمن والسلامة في الأنشطة الميدانية والاستكشافية."]}'::jsonb, settings='{}'::jsonb, styles='{}'::jsonb WHERE page_id = v_pid AND sort_order = 2;
  IF NOT FOUND THEN INSERT INTO page_sections (id, page_id, section_type, visible, sort_order, content, settings, styles) VALUES (gen_random_uuid(), v_pid, 'custom', TRUE, 2, '{"_renderer":"partnerAbout","eyebrow":"عن SENOTEC","heading":"SENOTEC","paragraphs":["SENOTEC هي شركة دولية متخصصة في تقديم الحلول التقنية والأمنية المتطورة. تمتلك الشركة خبرة واسعة في مجال أنظمة المراقبة والحماية الإلكترونية للمؤسسات والمنشآت.","نعمل مع الجمعية المغربية لهواة البحث والاستكشاف في إطار شراكة دولية تهدف إلى تعزيز الأمن والسلامة في الأنشطة الميدانية والاستكشافية."]}'::jsonb, '{}'::jsonb, '{}'::jsonb); END IF;
  UPDATE page_sections SET section_type = 'custom', content = '{"_renderer":"partnerContact","email":"contact@senotec.com","phone":"+212 522 000 000","website":"www.senotec.com","address":"شارع الحسن الثاني، الرباط، المغرب"}'::jsonb, settings='{}'::jsonb, styles='{}'::jsonb WHERE page_id = v_pid AND sort_order = 3;
  IF NOT FOUND THEN INSERT INTO page_sections (id, page_id, section_type, visible, sort_order, content, settings, styles) VALUES (gen_random_uuid(), v_pid, 'custom', TRUE, 3, '{"_renderer":"partnerContact","email":"contact@senotec.com","phone":"+212 522 000 000","website":"www.senotec.com","address":"شارع الحسن الثاني، الرباط، المغرب"}'::jsonb, '{}'::jsonb, '{}'::jsonb); END IF;
  UPDATE page_sections SET section_type = 'custom', content = '{"_renderer":"partnerCta","heading":"هل أنت مستعد للشراكة معنا؟","description":"","buttonLabel":"تواصل معنا","buttonUrl":"#prForm"}'::jsonb, settings='{}'::jsonb, styles='{}'::jsonb WHERE page_id = v_pid AND sort_order = 4;
  IF NOT FOUND THEN INSERT INTO page_sections (id, page_id, section_type, visible, sort_order, content, settings, styles) VALUES (gen_random_uuid(), v_pid, 'custom', TRUE, 4, '{"_renderer":"partnerCta","heading":"هل أنت مستعد للشراكة معنا؟","description":"","buttonLabel":"تواصل معنا","buttonUrl":"#prForm"}'::jsonb, '{}'::jsonb, '{}'::jsonb); END IF;
  RAISE NOTICE 'SENOTEC seeded';

  ----------------------------------------------------------------------------
  -- 3. ASTROMET
  ----------------------------------------------------------------------------
  SELECT id INTO v_pid FROM pages WHERE slug = '/partners/astromet' LIMIT 1;
  IF v_pid IS NULL THEN
    INSERT INTO pages (title, slug, status) VALUES ('ASTROMET', '/partners/astromet', 'published') RETURNING id INTO v_pid;
  END IF;
  UPDATE page_sections SET section_type = 'hero', content = '{"heading":"ASTROMET","subheading":"شريك استراتيجي","description":"شريك استراتيجي للجمعية المغربية لهواة البحث والاستكشاف، متخصص في مجال التنقيب والاستكشاف المعدني بالمغرب.","backgroundImage":"","buttons":[{"id":"btn-pr-website","label":"زيارة الموقع الإلكتروني","url":"#","variant":"primary"},{"id":"btn-pr-contact","label":"تواصل مع الشريك","url":"#prForm","variant":"secondary"}]}'::jsonb, settings='{}'::jsonb, styles='{}'::jsonb WHERE page_id = v_pid AND sort_order = 1;
  IF NOT FOUND THEN INSERT INTO page_sections (id, page_id, section_type, visible, sort_order, content, settings, styles) VALUES (gen_random_uuid(), v_pid, 'hero', TRUE, 1, '{"heading":"ASTROMET","subheading":"شريك استراتيجي","description":"شريك استراتيجي للجمعية المغربية لهواة البحث والاستكشاف، متخصص في مجال التنقيب والاستكشاف المعدني بالمغرب.","backgroundImage":"","buttons":[{"id":"btn-pr-website","label":"زيارة الموقع الإلكتروني","url":"#","variant":"primary"},{"id":"btn-pr-contact","label":"تواصل مع الشريك","url":"#prForm","variant":"secondary"}]}'::jsonb, '{}'::jsonb, '{}'::jsonb); END IF;
  UPDATE page_sections SET section_type = 'custom', content = '{"_renderer":"partnerAbout","eyebrow":"عن ASTROMET","heading":"ASTROMET","paragraphs":["ASTROMET هي شركة مغربية رائدة في مجال التنقيب والاستكشاف المعدني. تقوم الشركة على خبرة واسعة تمتد لسنوات عديدة في مجال الدراسات الجيولوجية والتنقيب عن المعادن.","نعمل مع الجمعية المغربية لهواة البحث والاستكشاف في إطار شراكة استراتيجية تهدف إلى تعزيز التعاون العلمي والتقني في مجالات الاستكشاف والبحث الميداني."]}'::jsonb, settings='{}'::jsonb, styles='{}'::jsonb WHERE page_id = v_pid AND sort_order = 2;
  IF NOT FOUND THEN INSERT INTO page_sections (id, page_id, section_type, visible, sort_order, content, settings, styles) VALUES (gen_random_uuid(), v_pid, 'custom', TRUE, 2, '{"_renderer":"partnerAbout","eyebrow":"عن ASTROMET","heading":"ASTROMET","paragraphs":["ASTROMET هي شركة مغربية رائدة في مجال التنقيب والاستكشاف المعدني. تقوم الشركة على خبرة واسعة تمتد لسنوات عديدة في مجال الدراسات الجيولوجية والتنقيب عن المعادن.","نعمل مع الجمعية المغربية لهواة البحث والاستكشاف في إطار شراكة استراتيجية تهدف إلى تعزيز التعاون العلمي والتقني في مجالات الاستكشاف والبحث الميداني."]}'::jsonb, '{}'::jsonb, '{}'::jsonb); END IF;
  UPDATE page_sections SET section_type = 'custom', content = '{"_renderer":"partnerContact","email":"contact@astromet.ma","phone":"+212 500 000 000","website":"www.astromet.ma","address":"شارع محمد الخامس، الدار البيضاء، المغرب"}'::jsonb, settings='{}'::jsonb, styles='{}'::jsonb WHERE page_id = v_pid AND sort_order = 3;
  IF NOT FOUND THEN INSERT INTO page_sections (id, page_id, section_type, visible, sort_order, content, settings, styles) VALUES (gen_random_uuid(), v_pid, 'custom', TRUE, 3, '{"_renderer":"partnerContact","email":"contact@astromet.ma","phone":"+212 500 000 000","website":"www.astromet.ma","address":"شارع محمد الخامس، الدار البيضاء، المغرب"}'::jsonb, '{}'::jsonb, '{}'::jsonb); END IF;
  UPDATE page_sections SET section_type = 'custom', content = '{"_renderer":"partnerCta","heading":"هل أنت مستعد للشراكة معنا؟","description":"","buttonLabel":"تواصل معنا","buttonUrl":"#prForm"}'::jsonb, settings='{}'::jsonb, styles='{}'::jsonb WHERE page_id = v_pid AND sort_order = 4;
  IF NOT FOUND THEN INSERT INTO page_sections (id, page_id, section_type, visible, sort_order, content, settings, styles) VALUES (gen_random_uuid(), v_pid, 'custom', TRUE, 4, '{"_renderer":"partnerCta","heading":"هل أنت مستعد للشراكة معنا؟","description":"","buttonLabel":"تواصل معنا","buttonUrl":"#prForm"}'::jsonb, '{}'::jsonb, '{}'::jsonb); END IF;
  RAISE NOTICE 'ASTROMET seeded';

  ----------------------------------------------------------------------------
  -- 4. AssociationDetectionCentre
  ----------------------------------------------------------------------------
  SELECT id INTO v_pid FROM pages WHERE slug = '/partners/detection-centre' LIMIT 1;
  IF v_pid IS NULL THEN
    INSERT INTO pages (title, slug, status) VALUES ('AssociationDetectionCentre', '/partners/detection-centre', 'published') RETURNING id INTO v_pid;
  END IF;
  UPDATE page_sections SET section_type = 'hero', content = '{"heading":"AssociationDetectionCentre","subheading":"شريك استراتيجي","description":"شريك استراتيجي للجمعية المغربية لهواة البحث والاستكشاف، مركز متخصص في الكشف والتنقيب والتدريب على استخدام أجهزة الاستكشاف.","backgroundImage":"","buttons":[{"id":"btn-pr-website","label":"زيارة الموقع الإلكتروني","url":"#","variant":"primary"},{"id":"btn-pr-contact","label":"تواصل مع الشريك","url":"#prForm","variant":"secondary"}]}'::jsonb, settings='{}'::jsonb, styles='{}'::jsonb WHERE page_id = v_pid AND sort_order = 1;
  IF NOT FOUND THEN INSERT INTO page_sections (id, page_id, section_type, visible, sort_order, content, settings, styles) VALUES (gen_random_uuid(), v_pid, 'hero', TRUE, 1, '{"heading":"AssociationDetectionCentre","subheading":"شريك استراتيجي","description":"شريك استراتيجي للجمعية المغربية لهواة البحث والاستكشاف، مركز متخصص في الكشف والتنقيب والتدريب على استخدام أجهزة الاستكشاف.","backgroundImage":"","buttons":[{"id":"btn-pr-website","label":"زيارة الموقع الإلكتروني","url":"#","variant":"primary"},{"id":"btn-pr-contact","label":"تواصل مع الشريك","url":"#prForm","variant":"secondary"}]}'::jsonb, '{}'::jsonb, '{}'::jsonb); END IF;
  UPDATE page_sections SET section_type = 'custom', content = '{"_renderer":"partnerAbout","eyebrow":"عن AssociationDetectionCentre","heading":"AssociationDetectionCentre","paragraphs":["AssociationDetectionCentre هو مركز متخصص في الكشف والتنقيب والتدريب على استخدام أحدث أجهزة الاستكشاف. يقدم المركز دورات تكوينية وورشات عملية لتطوير مهارات المنقبين والمستكشفين.","نعمل مع الجمعية المغربية لهواة البحث والاستكشاف في إطار شراكة استراتيجية تهدف إلى توفير التكوين والتدريب المتخصص لأعضاء الجمعية في مجال استخدام أجهزة الكشف والتنقيب."]}'::jsonb, settings='{}'::jsonb, styles='{}'::jsonb WHERE page_id = v_pid AND sort_order = 2;
  IF NOT FOUND THEN INSERT INTO page_sections (id, page_id, section_type, visible, sort_order, content, settings, styles) VALUES (gen_random_uuid(), v_pid, 'custom', TRUE, 2, '{"_renderer":"partnerAbout","eyebrow":"عن AssociationDetectionCentre","heading":"AssociationDetectionCentre","paragraphs":["AssociationDetectionCentre هو مركز متخصص في الكشف والتنقيب والتدريب على استخدام أحدث أجهزة الاستكشاف. يقدم المركز دورات تكوينية وورشات عملية لتطوير مهارات المنقبين والمستكشفين.","نعمل مع الجمعية المغربية لهواة البحث والاستكشاف في إطار شراكة استراتيجية تهدف إلى توفير التكوين والتدريب المتخصص لأعضاء الجمعية في مجال استخدام أجهزة الكشف والتنقيب."]}'::jsonb, '{}'::jsonb, '{}'::jsonb); END IF;
  UPDATE page_sections SET section_type = 'custom', content = '{"_renderer":"partnerContact","email":"contact@detection-centre.ma","phone":"+212 539 000 000","website":"www.detection-centre.ma","address":"شارع فلسطين، طنجة، المغرب"}'::jsonb, settings='{}'::jsonb, styles='{}'::jsonb WHERE page_id = v_pid AND sort_order = 3;
  IF NOT FOUND THEN INSERT INTO page_sections (id, page_id, section_type, visible, sort_order, content, settings, styles) VALUES (gen_random_uuid(), v_pid, 'custom', TRUE, 3, '{"_renderer":"partnerContact","email":"contact@detection-centre.ma","phone":"+212 539 000 000","website":"www.detection-centre.ma","address":"شارع فلسطين، طنجة، المغرب"}'::jsonb, '{}'::jsonb, '{}'::jsonb); END IF;
  UPDATE page_sections SET section_type = 'custom', content = '{"_renderer":"partnerCta","heading":"هل أنت مستعد للشراكة معنا؟","description":"","buttonLabel":"تواصل معنا","buttonUrl":"#prForm"}'::jsonb, settings='{}'::jsonb, styles='{}'::jsonb WHERE page_id = v_pid AND sort_order = 4;
  IF NOT FOUND THEN INSERT INTO page_sections (id, page_id, section_type, visible, sort_order, content, settings, styles) VALUES (gen_random_uuid(), v_pid, 'custom', TRUE, 4, '{"_renderer":"partnerCta","heading":"هل أنت مستعد للشراكة معنا؟","description":"","buttonLabel":"تواصل معنا","buttonUrl":"#prForm"}'::jsonb, '{}'::jsonb, '{}'::jsonb); END IF;
  RAISE NOTICE 'AssociationDetectionCentre seeded';

  ----------------------------------------------------------------------------
  -- 5. ANCPP
  ----------------------------------------------------------------------------
  SELECT id INTO v_pid FROM pages WHERE slug = '/partners/ancpp' LIMIT 1;
  IF v_pid IS NULL THEN
    INSERT INTO pages (title, slug, status) VALUES ('ANCPP', '/partners/ancpp', 'published') RETURNING id INTO v_pid;
  END IF;
  UPDATE page_sections SET section_type = 'hero', content = '{"heading":"ANCPP","subheading":"شريك وطني","description":"شريك وطني للجمعية المغربية لهواة البحث والاستكشاف، الجمعية الوطنية لمحترفي الصيد البحري بالمغرب.","backgroundImage":"","buttons":[{"id":"btn-pr-website","label":"زيارة الموقع الإلكتروني","url":"#","variant":"primary"},{"id":"btn-pr-contact","label":"تواصل مع الشريك","url":"#prForm","variant":"secondary"}]}'::jsonb, settings='{}'::jsonb, styles='{}'::jsonb WHERE page_id = v_pid AND sort_order = 1;
  IF NOT FOUND THEN INSERT INTO page_sections (id, page_id, section_type, visible, sort_order, content, settings, styles) VALUES (gen_random_uuid(), v_pid, 'hero', TRUE, 1, '{"heading":"ANCPP","subheading":"شريك وطني","description":"شريك وطني للجمعية المغربية لهواة البحث والاستكشاف، الجمعية الوطنية لمحترفي الصيد البحري بالمغرب.","backgroundImage":"","buttons":[{"id":"btn-pr-website","label":"زيارة الموقع الإلكتروني","url":"#","variant":"primary"},{"id":"btn-pr-contact","label":"تواصل مع الشريك","url":"#prForm","variant":"secondary"}]}'::jsonb, '{}'::jsonb, '{}'::jsonb); END IF;
  UPDATE page_sections SET section_type = 'custom', content = '{"_renderer":"partnerAbout","eyebrow":"عن ANCPP","heading":"ANCPP","paragraphs":["ANCPP هي الجمعية الوطنية لمحترفي الصيد البحري بالمغرب. تمثل الجمعية مصالح الصيادين المحترفين وتعمل على تطوير قطاع الصيد البحري وحماية الثروة السمكية الوطنية.","نعمل مع الجمعية المغربية لهواة البحث والاستكشاف في إطار شراكة وطنية تهدف إلى تعزيز التعاون في مجال الاستكشاف البحري وحماية البيئة البحرية المغربية."]}'::jsonb, settings='{}'::jsonb, styles='{}'::jsonb WHERE page_id = v_pid AND sort_order = 2;
  IF NOT FOUND THEN INSERT INTO page_sections (id, page_id, section_type, visible, sort_order, content, settings, styles) VALUES (gen_random_uuid(), v_pid, 'custom', TRUE, 2, '{"_renderer":"partnerAbout","eyebrow":"عن ANCPP","heading":"ANCPP","paragraphs":["ANCPP هي الجمعية الوطنية لمحترفي الصيد البحري بالمغرب. تمثل الجمعية مصالح الصيادين المحترفين وتعمل على تطوير قطاع الصيد البحري وحماية الثروة السمكية الوطنية.","نعمل مع الجمعية المغربية لهواة البحث والاستكشاف في إطار شراكة وطنية تهدف إلى تعزيز التعاون في مجال الاستكشاف البحري وحماية البيئة البحرية المغربية."]}'::jsonb, '{}'::jsonb, '{}'::jsonb); END IF;
  UPDATE page_sections SET section_type = 'custom', content = '{"_renderer":"partnerContact","email":"contact@ancpp.ma","phone":"+212 528 000 000","website":"www.ancpp.ma","address":"ميناء أكادير، أكادير، المغرب"}'::jsonb, settings='{}'::jsonb, styles='{}'::jsonb WHERE page_id = v_pid AND sort_order = 3;
  IF NOT FOUND THEN INSERT INTO page_sections (id, page_id, section_type, visible, sort_order, content, settings, styles) VALUES (gen_random_uuid(), v_pid, 'custom', TRUE, 3, '{"_renderer":"partnerContact","email":"contact@ancpp.ma","phone":"+212 528 000 000","website":"www.ancpp.ma","address":"ميناء أكادير، أكادير، المغرب"}'::jsonb, '{}'::jsonb, '{}'::jsonb); END IF;
  UPDATE page_sections SET section_type = 'custom', content = '{"_renderer":"partnerCta","heading":"هل أنت مستعد للشراكة معنا؟","description":"","buttonLabel":"تواصل معنا","buttonUrl":"#prForm"}'::jsonb, settings='{}'::jsonb, styles='{}'::jsonb WHERE page_id = v_pid AND sort_order = 4;
  IF NOT FOUND THEN INSERT INTO page_sections (id, page_id, section_type, visible, sort_order, content, settings, styles) VALUES (gen_random_uuid(), v_pid, 'custom', TRUE, 4, '{"_renderer":"partnerCta","heading":"هل أنت مستعد للشراكة معنا؟","description":"","buttonLabel":"تواصل معنا","buttonUrl":"#prForm"}'::jsonb, '{}'::jsonb, '{}'::jsonb); END IF;
  RAISE NOTICE 'ANCPP seeded';

  ----------------------------------------------------------------------------
  -- 6. OMSDS
  ----------------------------------------------------------------------------
  SELECT id INTO v_pid FROM pages WHERE slug = '/partners/omsds' LIMIT 1;
  IF v_pid IS NULL THEN
    INSERT INTO pages (title, slug, status) VALUES ('OMSDS', '/partners/omsds', 'published') RETURNING id INTO v_pid;
  END IF;
  UPDATE page_sections SET section_type = 'hero', content = '{"heading":"OMSDS","subheading":"شريك رئيسي","description":"شريك رئيسي للجمعية المغربية لهواة البحث والاستكشاف، منظمة مغربية للتنمية الاجتماعية والتضامن تعمل على دعم المبادرات المجتمعية.","backgroundImage":"","buttons":[{"id":"btn-pr-website","label":"زيارة الموقع الإلكتروني","url":"#","variant":"primary"},{"id":"btn-pr-contact","label":"تواصل مع الشريك","url":"#prForm","variant":"secondary"}]}'::jsonb, settings='{}'::jsonb, styles='{}'::jsonb WHERE page_id = v_pid AND sort_order = 1;
  IF NOT FOUND THEN INSERT INTO page_sections (id, page_id, section_type, visible, sort_order, content, settings, styles) VALUES (gen_random_uuid(), v_pid, 'hero', TRUE, 1, '{"heading":"OMSDS","subheading":"شريك رئيسي","description":"شريك رئيسي للجمعية المغربية لهواة البحث والاستكشاف، منظمة مغربية للتنمية الاجتماعية والتضامن تعمل على دعم المبادرات المجتمعية.","backgroundImage":"","buttons":[{"id":"btn-pr-website","label":"زيارة الموقع الإلكتروني","url":"#","variant":"primary"},{"id":"btn-pr-contact","label":"تواصل مع الشريك","url":"#prForm","variant":"secondary"}]}'::jsonb, '{}'::jsonb, '{}'::jsonb); END IF;
  UPDATE page_sections SET section_type = 'custom', content = '{"_renderer":"partnerAbout","eyebrow":"عن OMSDS","heading":"OMSDS","paragraphs":["OMSDS هي منظمة مغربية للتنمية الاجتماعية والتضامن، تعمل على دعم وتمكين المجتمع المدني من خلال برامج تنموية واجتماعية متنوعة تستهدف الفئات المحتاجة.","نعمل مع الجمعية المغربية لهواة البحث والاستكشاف في إطار شراكة مجتمعية تهدف إلى دعم الأنشطة الاجتماعية والتطوعية وتعزيز قيم التضامن والتكافل."]}'::jsonb, settings='{}'::jsonb, styles='{}'::jsonb WHERE page_id = v_pid AND sort_order = 2;
  IF NOT FOUND THEN INSERT INTO page_sections (id, page_id, section_type, visible, sort_order, content, settings, styles) VALUES (gen_random_uuid(), v_pid, 'custom', TRUE, 2, '{"_renderer":"partnerAbout","eyebrow":"عن OMSDS","heading":"OMSDS","paragraphs":["OMSDS هي منظمة مغربية للتنمية الاجتماعية والتضامن، تعمل على دعم وتمكين المجتمع المدني من خلال برامج تنموية واجتماعية متنوعة تستهدف الفئات المحتاجة.","نعمل مع الجمعية المغربية لهواة البحث والاستكشاف في إطار شراكة مجتمعية تهدف إلى دعم الأنشطة الاجتماعية والتطوعية وتعزيز قيم التضامن والتكافل."]}'::jsonb, '{}'::jsonb, '{}'::jsonb); END IF;
  UPDATE page_sections SET section_type = 'custom', content = '{"_renderer":"partnerContact","email":"contact@omsds.org","phone":"+212 537 000 000","website":"www.omsds.org","address":"شارع محمد السادس، مراكش، المغرب"}'::jsonb, settings='{}'::jsonb, styles='{}'::jsonb WHERE page_id = v_pid AND sort_order = 3;
  IF NOT FOUND THEN INSERT INTO page_sections (id, page_id, section_type, visible, sort_order, content, settings, styles) VALUES (gen_random_uuid(), v_pid, 'custom', TRUE, 3, '{"_renderer":"partnerContact","email":"contact@omsds.org","phone":"+212 537 000 000","website":"www.omsds.org","address":"شارع محمد السادس، مراكش، المغرب"}'::jsonb, '{}'::jsonb, '{}'::jsonb); END IF;
  UPDATE page_sections SET section_type = 'custom', content = '{"_renderer":"partnerCta","heading":"هل أنت مستعد للشراكة معنا؟","description":"","buttonLabel":"تواصل معنا","buttonUrl":"#prForm"}'::jsonb, settings='{}'::jsonb, styles='{}'::jsonb WHERE page_id = v_pid AND sort_order = 4;
  IF NOT FOUND THEN INSERT INTO page_sections (id, page_id, section_type, visible, sort_order, content, settings, styles) VALUES (gen_random_uuid(), v_pid, 'custom', TRUE, 4, '{"_renderer":"partnerCta","heading":"هل أنت مستعد للشراكة معنا؟","description":"","buttonLabel":"تواصل معنا","buttonUrl":"#prForm"}'::jsonb, '{}'::jsonb, '{}'::jsonb); END IF;
  RAISE NOTICE 'OMSDS seeded';

  RAISE NOTICE '=========================================';
  RAISE NOTICE 'ALL 6 PARTNER PAGES SEEDED';
  RAISE NOTICE '=========================================';
END $$;
