-- ============================================================================
-- Our Partners — Bilingual Conversion (_ar/_fr) for ALL 6 partner pages
-- Idempotent. Arabic sourced from existing seed migrations (00008-00016).
-- Shared sections (services/why/gallery) get French translations.
-- Partner-specific sections get Arabic preserved; French left for CMS entry.
-- ============================================================================

DO $$
DECLARE
  v_pid uuid;
BEGIN
  -- #################################################################
  -- 1. LeFouilleurma  (/partners/lefouilleurma)
  -- #################################################################
  SELECT id INTO v_pid FROM pages WHERE slug = '/partners/lefouilleurma' LIMIT 1;
  IF v_pid IS NOT NULL THEN

    -- 1. HERO
    UPDATE page_sections SET content = '{"heading_ar":"LeFouilleurma","heading_fr":"LeFouilleurma","subheading_ar":"شريك وطني","subheading_fr":"Partenaire national","description_ar":"شريك وطني للجمعية المغربية لهواة البحث والاستكشاف، متخصص في بيع وشراء أجهزة الكشف عن المعادن والكنوز على المستوى الوطني.","description_fr":"Partenaire national de l''Association Marocaine des Amateurs de Recherche et d''Exploration, spécialisé dans la vente et l''achat de détecteurs de métaux et de trésors au niveau national.","backgroundImage":"","buttons":[{"id":"btn-pr-website","label_ar":"زيارة الموقع الإلكتروني","label_fr":"Visiter le site web","url":"https://www.lefouilleurma.ma","variant":"primary"},{"id":"btn-pr-contact","label_ar":"تواصل مع الشريك","label_fr":"Contacter le partenaire","url":"#prForm","variant":"secondary"}]}'::jsonb WHERE page_id = v_pid AND sort_order = 1;

    -- 2. ABOUT
    UPDATE page_sections SET content = '{"_renderer":"partnerAbout","eyebrow_ar":"عن LeFouilleurma","eyebrow_fr":"À propos de LeFouilleurma","heading_ar":"شريككم الموثوق في مجال التنقيب والاستكشاف","heading_fr":"Votre partenaire de confiance en prospection et exploration","paragraphs_ar":["LeFouilleurma هي شركة مغربية متخصصة في بيع وشراء أجهزة الكشف عن المعادن والكنوز. تقدم الشركة مجموعة واسعة من الأجهزة المتطورة لتلبية احتياجات الهواة والمحترفين على حد سواء.","نعمل مع الجمعية المغربية لهواة البحث والاستكشاف في إطار شراكة وطنية تهدف إلى توفير أحدث أجهزة الكشف والتنقيب لأعضاء الجمعية بأسعار تفضيلية."],"paragraphs_fr":["LeFouilleurma est une entreprise marocaine spécialisée dans la vente et l''achat de détecteurs de métaux et de trésors. L''entreprise propose une large gamme d''appareils avancés pour répondre aux besoins des amateurs et des professionnels.","Nous travaillons avec l''Association Marocaine des Amateurs de Recherche et d''Exploration dans le cadre d''un partenariat national visant à fournir les derniers équipements de détection et de prospection aux membres de l''association à des prix préférentiels."],"image":""}'::jsonb WHERE page_id = v_pid AND sort_order = 2;

    -- 3. SERVICES
    UPDATE page_sections SET content = '{"_renderer":"partnerServices","eyebrow_ar":"خدماتنا","eyebrow_fr":"Nos services","heading_ar":"ماذا نقدم؟","heading_fr":"Que proposons-nous ?","description_ar":"نقدم مجموعة متكاملة من الخدمات المتخصصة في مجال التنقيب والاستكشاف.","description_fr":"Nous offrons une gamme complète de services spécialisés en prospection et exploration.","cards":[{"title_ar":"التنقيب المعدني","title_fr":"Prospection minière","description_ar":"دراسات جيولوجية متقدمة للتنقيب عن المعادن والثروات الطبيعية في مختلف مناطق المغرب.","description_fr":"Études géologiques avancées pour la prospection des minéraux et des ressources naturelles dans les différentes régions du Maroc."},{"title_ar":"الدراسات الجيولوجية","title_fr":"Études géologiques","description_ar":"تحليل وتوثيق التكوينات الجيولوجية وتقديم استشارات متخصصة للمشاريع الاستكشافية.","description_fr":"Analyse et documentation des formations géologiques et conseil spécialisé pour les projets d''exploration."},{"title_ar":"رسم الخرائط","title_fr":"Cartographie","description_ar":"تصميم وإنتاج خرائط جيولوجية وطبوغرافية دقيقة باستخدام أحدث التقنيات الرقمية.","description_fr":"Conception et production de cartes géologiques et topographiques précises utilisant les dernières technologies numériques."},{"title_ar":"التحاليل المخبرية","title_fr":"Analyses en laboratoire","description_ar":"تحاليل متطورة للعينات المعدنية والصخرية باستخدام أحدث الأجهزة والتقنيات المخبرية.","description_fr":"Analyses avancées d''échantillons minéraux et rocheux utilisant les derniers équipements et techniques de laboratoire."}]}'::jsonb WHERE page_id = v_pid AND sort_order = 3;

    -- 4. WHY PARTNER
    UPDATE page_sections SET content = '{"_renderer":"partnerWhy","eyebrow_ar":"لماذا الشراكة معنا؟","eyebrow_fr":"Pourquoi un partenariat avec nous ?","heading_ar":"مميزات شراكتنا","heading_fr":"Les avantages de notre partenariat","description_ar":"نعمل جنبًا إلى جنب مع شركائنا لتحقيق النجاح المشترك.","description_fr":"Nous travaillons main dans la main avec nos partenaires pour atteindre le succès commun.","cards":[{"title_ar":"خبرة مهنية","title_fr":"Expertise professionnelle","description_ar":"نمتلك خبرة تمتد لسنوات في مجال التنقيب والاستكشاف المعدني بالمغرب.","description_fr":"Nous possédons une expérience de plusieurs années dans le domaine de la prospection et de l''exploration minière au Maroc."},{"title_ar":"شريك موثوق","title_fr":"Partenaire fiable","description_ar":"نلتزم بأعلى معايير الجودة والمهنية في جميع مشاريعنا وخدماتنا.","description_fr":"Nous respectons les plus hauts standards de qualité et de professionnalisme dans tous nos projets et services."},{"title_ar":"خدمات عالية الجودة","title_fr":"Services de haute qualité","description_ar":"نقدم خدمات متكاملة تلبي احتياجات شركائنا بأعلى مستوى من الدقة والكفاءة.","description_fr":"Nous offrons des services complets répondant aux besoins de nos partenaires avec le plus haut niveau de précision et d''efficacité."},{"title_ar":"تعاون وطني ودولي","title_fr":"Coopération nationale et internationale","description_ar":"نعمل في إطار تعاون وطني ودولي لتعزيز البحث والاستكشاف المعدني.","description_fr":"Nous travaillons dans le cadre d''une coopération nationale et internationale pour promouvoir la recherche et l''exploration minière."}]}'::jsonb WHERE page_id = v_pid AND sort_order = 4;

    -- 5. GALLERY
    UPDATE page_sections SET content = '{"_renderer":"partnerGallery","eyebrow_ar":"معرض الصور","eyebrow_fr":"Galerie photos","heading_ar":"صور من أعمالنا","heading_fr":"Photos de nos travaux","description_ar":"جانب من أنشطتنا ومشاريعنا المشتركة.","description_fr":"Un aperçu de nos activités et projets communs.","images":[{"id":"gimg-0","url":"","alt":""},{"id":"gimg-1","url":"","alt":""},{"id":"gimg-2","url":"","alt":""},{"id":"gimg-3","url":"","alt":""},{"id":"gimg-4","url":"","alt":""},{"id":"gimg-5","url":"","alt":""}]}'::jsonb WHERE page_id = v_pid AND sort_order = 5;

    -- 6. CONTACT
    UPDATE page_sections SET content = '{"_renderer":"partnerContact","heading_ar":"تواصل معنا","heading_fr":"Contactez-nous","description_ar":"نحن هنا للإجابة على استفساراتكم.","description_fr":"Nous sommes là pour répondre à vos questions.","email":"contact@lefouilleurma.ma","phone":"+212 666 000 000","website":"www.lefouilleurma.ma","address":"شارع الزرقطوني، أكادير، المغرب"}'::jsonb WHERE page_id = v_pid AND sort_order = 6;

    -- 7. FORM
    UPDATE page_sections SET content = '{"_renderer":"partnerForm","heading_ar":"تواصل مع LeFouilleurma","heading_fr":"Contacter LeFouilleurma","description_ar":"أرسل لنا استفسارك وسنرد عليك في أقرب وقت.","description_fr":"Envoyez-nous votre demande et nous vous répondrons dans les plus brefs délais."}'::jsonb WHERE page_id = v_pid AND sort_order = 7;

    -- 8. CTA
    UPDATE page_sections SET content = '{"_renderer":"partnerCta","heading_ar":"هل أنت مهتم بالعمل مع هذا الشريك؟","heading_fr":"Intéressé par un partenariat ?","description":"","buttons":[{"id":"btn-pr-cta-0","label_ar":"زيارة الموقع الإلكتروني","label_fr":"Visiter le site web","url":"https://www.lefouilleurma.ma","variant":"primary"},{"id":"btn-pr-cta-1","label_ar":"تواصل مع الشريك","label_fr":"Contacter le partenaire","url":"#prForm","variant":"secondary"}]}'::jsonb WHERE page_id = v_pid AND sort_order = 8;

    RAISE NOTICE 'LeFouilleurma: sections updated.';
  END IF;

  -- #################################################################
  -- 2. SENOTEC  (/partners/scnotce)
  -- #################################################################
  SELECT id INTO v_pid FROM pages WHERE slug = '/partners/scnotce' LIMIT 1;
  IF v_pid IS NOT NULL THEN

    UPDATE page_sections SET content = '{"heading_ar":"SENOTEC","heading_fr":"SENOTEC","subheading_ar":"شريك دولي","subheading_fr":"Partenaire international","description_ar":"شريك دولي للجمعية المغربية لهواة البحث والاستكشاف، متخصص في الحلول التقنية والأمنية المتطورة على المستوى الدولي.","description_fr":"Partenaire international de l''Association Marocaine des Amateurs de Recherche et d''Exploration, spécialisé dans les solutions techniques et de sécurité avancées au niveau international.","backgroundImage":"","buttons":[{"id":"btn-pr-website","label_ar":"زيارة الموقع الإلكتروني","label_fr":"Visiter le site web","url":"https://www.senotec.com","variant":"primary"},{"id":"btn-pr-contact","label_ar":"تواصل مع الشريك","label_fr":"Contacter le partenaire","url":"#prForm","variant":"secondary"}]}'::jsonb WHERE page_id = v_pid AND sort_order = 1;

    UPDATE page_sections SET content = '{"_renderer":"partnerAbout","eyebrow_ar":"عن SENOTEC","eyebrow_fr":"À propos de SENOTEC","heading_ar":"شريككم الموثوق في مجال التنقيب والاستكشاف","heading_fr":"Votre partenaire de confiance en prospection et exploration","paragraphs_ar":["SENOTEC هي شركة دولية متخصصة في تقديم الحلول التقنية والأمنية المتطورة. تمتلك الشركة خبرة واسعة في مجال أنظمة المراقبة والحماية الإلكترونية للمؤسسات والمنشآت.","نعمل مع الجمعية المغربية لهواة البحث والاستكشاف في إطار شراكة دولية تهدف إلى تعزيز الأمن والسلامة في الأنشطة الميدانية والاستكشافية."],"paragraphs_fr":["SENOTEC est une entreprise internationale spécialisée dans les solutions techniques et de sécurité avancées. L''entreprise possède une vaste expérience dans les systèmes de surveillance et de protection électronique pour les institutions et les installations.","Nous travaillons avec l''Association Marocaine des Amateurs de Recherche et d''Exploration dans le cadre d''un partenariat international visant à renforcer la sécurité dans les activités de terrain et d''exploration."],"image":""}'::jsonb WHERE page_id = v_pid AND sort_order = 2;

    -- services identical to lefouilleurma
    UPDATE page_sections SET content = '{"_renderer":"partnerServices","eyebrow_ar":"خدماتنا","eyebrow_fr":"Nos services","heading_ar":"ماذا نقدم؟","heading_fr":"Que proposons-nous ?","description_ar":"نقدم مجموعة متكاملة من الخدمات المتخصصة في مجال التنقيب والاستكشاف.","description_fr":"Nous offrons une gamme complète de services spécialisés en prospection et exploration.","cards":[{"title_ar":"التنقيب المعدني","title_fr":"Prospection minière","description_ar":"دراسات جيولوجية متقدمة للتنقيب عن المعادن والثروات الطبيعية في مختلف مناطق المغرب.","description_fr":"Études géologiques avancées pour la prospection des minéraux et des ressources naturelles dans les différentes régions du Maroc."},{"title_ar":"الدراسات الجيولوجية","title_fr":"Études géologiques","description_ar":"تحليل وتوثيق التكوينات الجيولوجية وتقديم استشارات متخصصة للمشاريع الاستكشافية.","description_fr":"Analyse et documentation des formations géologiques et conseil spécialisé pour les projets d''exploration."},{"title_ar":"رسم الخرائط","title_fr":"Cartographie","description_ar":"تصميم وإنتاج خرائط جيولوجية وطبوغرافية دقيقة باستخدام أحدث التقنيات الرقمية.","description_fr":"Conception et production de cartes géologiques et topographiques précises utilisant les dernières technologies numériques."},{"title_ar":"التحاليل المخبرية","title_fr":"Analyses en laboratoire","description_ar":"تحاليل متطورة للعينات المعدنية والصخرية باستخدام أحدث الأجهزة والتقنيات المخبرية.","description_fr":"Analyses avancées d''échantillons minéraux et rocheux utilisant les derniers équipements et techniques de laboratoire."}]}'::jsonb WHERE page_id = v_pid AND sort_order = 3;

    -- why identical
    UPDATE page_sections SET content = '{"_renderer":"partnerWhy","eyebrow_ar":"لماذا الشراكة معنا؟","eyebrow_fr":"Pourquoi un partenariat avec nous ?","heading_ar":"مميزات شراكتنا","heading_fr":"Les avantages de notre partenariat","description_ar":"نعمل جنبًا إلى جنب مع شركائنا لتحقيق النجاح المشترك.","description_fr":"Nous travaillons main dans la main avec nos partenaires pour atteindre le succès commun.","cards":[{"title_ar":"خبرة مهنية","title_fr":"Expertise professionnelle","description_ar":"نمتلك خبرة تمتد لسنوات في مجال التنقيب والاستكشاف المعدني بالمغرب.","description_fr":"Nous possédons une expérience de plusieurs années en prospection et exploration minière au Maroc."},{"title_ar":"شريك موثوق","title_fr":"Partenaire fiable","description_ar":"نلتزم بأعلى معايير الجودة والمهنية في جميع مشاريعنا وخدماتنا.","description_fr":"Nous respectons les plus hauts standards de qualité dans tous nos projets."},{"title_ar":"خدمات عالية الجودة","title_fr":"Services de haute qualité","description_ar":"نقدم خدمات متكاملة تلبي احتياجات شركائنا بأعلى مستوى من الدقة والكفاءة.","description_fr":"Nous offrons des services complets avec le plus haut niveau de précision."},{"title_ar":"تعاون وطني ودولي","title_fr":"Coopération nationale et internationale","description_ar":"نعمل في إطار تعاون وطني ودولي لتعزيز البحث والاستكشاف المعدني.","description_fr":"Nous travaillons en coopération nationale et internationale pour promouvoir la recherche minière."}]}'::jsonb WHERE page_id = v_pid AND sort_order = 4;

    UPDATE page_sections SET content = '{"_renderer":"partnerGallery","eyebrow_ar":"معرض الصور","eyebrow_fr":"Galerie photos","heading_ar":"صور من أعمالنا","heading_fr":"Photos de nos travaux","description_ar":"جانب من أنشطتنا ومشاريعنا المشتركة.","description_fr":"Un aperçu de nos activités et projets communs.","images":[{"id":"gimg-0","url":"","alt":""},{"id":"gimg-1","url":"","alt":""},{"id":"gimg-2","url":"","alt":""},{"id":"gimg-3","url":"","alt":""},{"id":"gimg-4","url":"","alt":""},{"id":"gimg-5","url":"","alt":""}]}'::jsonb WHERE page_id = v_pid AND sort_order = 5;

    UPDATE page_sections SET content = '{"_renderer":"partnerContact","heading_ar":"تواصل معنا","heading_fr":"Contactez-nous","description_ar":"نحن هنا للإجابة على استفساراتكم.","description_fr":"Nous sommes là pour répondre à vos questions.","email":"contact@senotec.com","phone":"+212 522 000 000","website":"www.senotec.com","address":"شارع الحسن الثاني، الرباط، المغرب"}'::jsonb WHERE page_id = v_pid AND sort_order = 6;

    UPDATE page_sections SET content = '{"_renderer":"partnerForm","heading_ar":"تواصل مع SENOTEC","heading_fr":"Contacter SENOTEC","description_ar":"أرسل لنا استفسارك وسنرد عليك في أقرب وقت.","description_fr":"Envoyez-nous votre demande et nous vous répondrons dans les plus brefs délais."}'::jsonb WHERE page_id = v_pid AND sort_order = 7;

    UPDATE page_sections SET content = '{"_renderer":"partnerCta","heading_ar":"هل أنت مهتم بالعمل مع هذا الشريك؟","heading_fr":"Intéressé par un partenariat ?","description":"","buttons":[{"id":"btn-pr-cta-0","label_ar":"زيارة الموقع الإلكتروني","label_fr":"Visiter le site web","url":"https://www.lefouilleurma.ma","variant":"primary"},{"id":"btn-pr-cta-1","label_ar":"تواصل مع الشريك","label_fr":"Contacter le partenaire","url":"#prForm","variant":"secondary"}]}'::jsonb WHERE page_id = v_pid AND sort_order = 8;

    RAISE NOTICE 'SENOTEC: sections updated.';
  END IF;

  -- #################################################################
  -- 3. ASTROMET  (/partners/astromet)
  -- #################################################################
  SELECT id INTO v_pid FROM pages WHERE slug = '/partners/astromet' LIMIT 1;
  IF v_pid IS NOT NULL THEN

    UPDATE page_sections SET content = '{"heading_ar":"ASTROMET","heading_fr":"ASTROMET","subheading_ar":"شريك استراتيجي","subheading_fr":"Partenaire stratégique","description_ar":"شريك استراتيجي للجمعية المغربية لهواة البحث والاستكشاف، متخصص في مجال التنقيب والاستكشاف المعدني بالمغرب.","description_fr":"Partenaire stratégique de l''Association Marocaine des Amateurs de Recherche et d''Exploration, spécialisé dans la prospection et l''exploration minière au Maroc.","backgroundImage":"","buttons":[{"id":"btn-pr-website","label_ar":"زيارة الموقع الإلكتروني","label_fr":"Visiter le site web","url":"https://www.astromet.ma","variant":"primary"},{"id":"btn-pr-contact","label_ar":"تواصل مع الشريك","label_fr":"Contacter le partenaire","url":"#prForm","variant":"secondary"}]}'::jsonb WHERE page_id = v_pid AND sort_order = 1;

    UPDATE page_sections SET content = '{"_renderer":"partnerAbout","eyebrow_ar":"عن ASTROMET","eyebrow_fr":"À propos d''ASTROMET","heading_ar":"شريككم الموثوق في مجال التنقيب والاستكشاف","heading_fr":"Votre partenaire de confiance en prospection et exploration","paragraphs_ar":["ASTROMET هي شركة مغربية رائدة في مجال التنقيب والاستكشاف المعدني. تقوم الشركة على خبرة واسعة تمتد لسنوات عديدة في مجال الدراسات الجيولوجية والتنقيب عن المعادن.","نعمل مع الجمعية المغربية لهواة البحث والاستكشاف في إطار شراكة استراتيجية تهدف إلى تطوير مجال التنقيب والاستكشاف المعدني بالمغرب."],"paragraphs_fr":["ASTROMET est une entreprise marocaine leader dans le domaine de la prospection et de l''exploration minière. L''entreprise s''appuie sur une vaste expérience de nombreuses années dans les études géologiques et la prospection minière.","Nous travaillons avec l''Association Marocaine des Amateurs de Recherche et d''Exploration dans le cadre d''un partenariat stratégique visant à développer le secteur de la prospection et de l''exploration minière au Maroc."],"image":""}'::jsonb WHERE page_id = v_pid AND sort_order = 2;

    -- shared services / why / gallery
    UPDATE page_sections SET content = '{"_renderer":"partnerServices","eyebrow_ar":"خدماتنا","eyebrow_fr":"Nos services","heading_ar":"ماذا نقدم؟","heading_fr":"Que proposons-nous ?","description_ar":"نقدم مجموعة متكاملة من الخدمات المتخصصة في مجال التنقيب والاستكشاف.","description_fr":"Nous offrons une gamme complète de services spécialisés en prospection et exploration.","cards":[{"title_ar":"التنقيب المعدني","title_fr":"Prospection minière","description_ar":"دراسات جيولوجية متقدمة للتنقيب عن المعادن والثروات الطبيعية في مختلف مناطق المغرب.","description_fr":"Études géologiques avancées pour la prospection des minéraux et des ressources naturelles dans les différentes régions du Maroc."},{"title_ar":"الدراسات الجيولوجية","title_fr":"Études géologiques","description_ar":"تحليل وتوثيق التكوينات الجيولوجية وتقديم استشارات متخصصة للمشاريع الاستكشافية.","description_fr":"Analyse et documentation des formations géologiques et conseil spécialisé pour les projets d''exploration."},{"title_ar":"رسم الخرائط","title_fr":"Cartographie","description_ar":"تصميم وإنتاج خرائط جيولوجية وطبوغرافية دقيقة باستخدام أحدث التقنيات الرقمية.","description_fr":"Conception et production de cartes géologiques et topographiques précises utilisant les dernières technologies numériques."},{"title_ar":"التحاليل المخبرية","title_fr":"Analyses en laboratoire","description_ar":"تحاليل متطورة للعينات المعدنية والصخرية باستخدام أحدث الأجهزة والتقنيات المخبرية.","description_fr":"Analyses avancées d''échantillons minéraux et rocheux utilisant les derniers équipements et techniques de laboratoire."}]}'::jsonb WHERE page_id = v_pid AND sort_order = 3;

    UPDATE page_sections SET content = '{"_renderer":"partnerWhy","eyebrow_ar":"لماذا الشراكة معنا؟","eyebrow_fr":"Pourquoi un partenariat avec nous ?","heading_ar":"مميزات شراكتنا","heading_fr":"Les avantages de notre partenariat","description_ar":"نعمل جنبًا إلى جنب مع شركائنا لتحقيق النجاح المشترك.","description_fr":"Nous travaillons main dans la main avec nos partenaires pour atteindre le succès commun.","cards":[{"title_ar":"خبرة مهنية","title_fr":"Expertise professionnelle","description_ar":"نمتلك خبرة تمتد لسنوات في مجال التنقيب والاستكشاف المعدني بالمغرب.","description_fr":"Nous possédons une expérience de plusieurs années en prospection et exploration minière au Maroc."},{"title_ar":"شريك موثوق","title_fr":"Partenaire fiable","description_ar":"نلتزم بأعلى معايير الجودة والمهنية في جميع مشاريعنا وخدماتنا.","description_fr":"Nous respectons les plus hauts standards de qualité dans tous nos projets."},{"title_ar":"خدمات عالية الجودة","title_fr":"Services de haute qualité","description_ar":"نقدم خدمات متكاملة تلبي احتياجات شركائنا بأعلى مستوى من الدقة والكفاءة.","description_fr":"Nous offrons des services complets avec le plus haut niveau de précision."},{"title_ar":"تعاون وطني ودولي","title_fr":"Coopération nationale et internationale","description_ar":"نعمل في إطار تعاون وطني ودولي لتعزيز البحث والاستكشاف المعدني.","description_fr":"Nous travaillons en coopération nationale et internationale pour promouvoir la recherche minière."}]}'::jsonb WHERE page_id = v_pid AND sort_order = 4;

    UPDATE page_sections SET content = '{"_renderer":"partnerGallery","eyebrow_ar":"معرض الصور","eyebrow_fr":"Galerie photos","heading_ar":"صور من أعمالنا","heading_fr":"Photos de nos travaux","description_ar":"جانب من أنشطتنا ومشاريعنا المشتركة.","description_fr":"Un aperçu de nos activités et projets communs.","images":[{"id":"gimg-0","url":"","alt":""},{"id":"gimg-1","url":"","alt":""},{"id":"gimg-2","url":"","alt":""},{"id":"gimg-3","url":"","alt":""},{"id":"gimg-4","url":"","alt":""},{"id":"gimg-5","url":"","alt":""}]}'::jsonb WHERE page_id = v_pid AND sort_order = 5;

    UPDATE page_sections SET content = '{"_renderer":"partnerContact","heading_ar":"تواصل معنا","heading_fr":"Contactez-nous","description_ar":"نحن هنا للإجابة على استفساراتكم.","description_fr":"Nous sommes là pour répondre à vos questions.","email":"contact@astromet.ma","phone":"+212 500 000 000","website":"www.astromet.ma","address":"شارع محمد الخامس، الدار البيضاء، المغرب"}'::jsonb WHERE page_id = v_pid AND sort_order = 6;

    UPDATE page_sections SET content = '{"_renderer":"partnerForm","heading_ar":"تواصل مع ASTROMET","heading_fr":"Contacter ASTROMET","description_ar":"أرسل لنا استفسارك وسنرد عليك في أقرب وقت.","description_fr":"Envoyez-nous votre demande et nous vous répondrons dans les plus brefs délais."}'::jsonb WHERE page_id = v_pid AND sort_order = 7;

    UPDATE page_sections SET content = '{"_renderer":"partnerCta","heading_ar":"هل أنت مهتم بالعمل مع هذا الشريك؟","heading_fr":"Intéressé par un partenariat ?","description":"","buttons":[{"id":"btn-pr-cta-0","label_ar":"زيارة الموقع الإلكتروني","label_fr":"Visiter le site web","url":"https://www.lefouilleurma.ma","variant":"primary"},{"id":"btn-pr-cta-1","label_ar":"تواصل مع الشريك","label_fr":"Contacter le partenaire","url":"#prForm","variant":"secondary"}]}'::jsonb WHERE page_id = v_pid AND sort_order = 8;

    RAISE NOTICE 'ASTROMET: sections updated.';
  END IF;

  -- #################################################################
  -- 4. ANCPP  (/partners/ancpp)
  -- #################################################################
  SELECT id INTO v_pid FROM pages WHERE slug = '/partners/ancpp' LIMIT 1;
  IF v_pid IS NOT NULL THEN

    UPDATE page_sections SET content = '{"heading_ar":"ANCPP","heading_fr":"ANCPP","subheading_ar":"شريك وطني","subheading_fr":"Partenaire national","description_ar":"شريك وطني للجمعية المغربية لهواة البحث والاستكشاف، متخصص في قطاع الصيد البحري بالمغرب.","description_fr":"Partenaire national de l''Association Marocaine des Amateurs de Recherche et d''Exploration, spécialisé dans le secteur de la pêche maritime au Maroc.","backgroundImage":"","buttons":[{"id":"btn-pr-website","label_ar":"زيارة الموقع الإلكتروني","label_fr":"Visiter le site web","url":"#","variant":"primary"},{"id":"btn-pr-contact","label_ar":"تواصل مع الشريك","label_fr":"Contacter le partenaire","url":"#prForm","variant":"secondary"}]}'::jsonb WHERE page_id = v_pid AND sort_order = 1;

    UPDATE page_sections SET content = '{"_renderer":"partnerAbout","eyebrow_ar":"عن ANCPP","eyebrow_fr":"À propos d''ANCPP","heading_ar":"شريككم الموثوق في مجال التنقيب والاستكشاف","heading_fr":"Votre partenaire de confiance","paragraphs_ar":["الغرفة الوطنية للصيد البحري وتربية الأحياء المائية هي مؤسسة وطنية تمثل مصالح مهنيي قطاع الصيد البحري بالمغرب.","نعمل مع الجمعية المغربية لهواة البحث والاستكشاف في إطار شراكة وطنية لتعزيز الأنشطة البحرية والاستكشافية."],"paragraphs_fr":["La Chambre Nationale des Pêches Maritimes et de l''Aquaculture est une institution nationale représentant les intérêts des professionnels du secteur de la pêche maritime au Maroc.","Nous travaillons avec l''Association Marocaine des Amateurs de Recherche et d''Exploration dans le cadre d''un partenariat national pour renforcer les activités maritimes et d''exploration."],"image":""}'::jsonb WHERE page_id = v_pid AND sort_order = 2;

    -- shared services / why / gallery
    UPDATE page_sections SET content = '{"_renderer":"partnerServices","eyebrow_ar":"خدماتنا","eyebrow_fr":"Nos services","heading_ar":"ماذا نقدم؟","heading_fr":"Que proposons-nous ?","description_ar":"نقدم مجموعة متكاملة من الخدمات المتخصصة في مجال التنقيب والاستكشاف.","description_fr":"Nous offrons une gamme complète de services spécialisés en prospection et exploration.","cards":[{"title_ar":"التنقيب المعدني","title_fr":"Prospection minière","description_ar":"دراسات جيولوجية متقدمة للتنقيب عن المعادن والثروات الطبيعية في مختلف مناطق المغرب.","description_fr":"Études géologiques avancées pour la prospection des minéraux et des ressources naturelles."},{"title_ar":"الدراسات الجيولوجية","title_fr":"Études géologiques","description_ar":"تحليل وتوثيق التكوينات الجيولوجية وتقديم استشارات متخصصة للمشاريع الاستكشافية.","description_fr":"Analyse et documentation des formations géologiques et conseil spécialisé."},{"title_ar":"رسم الخرائط","title_fr":"Cartographie","description_ar":"تصميم وإنتاج خرائط جيولوجية وطبوغرافية دقيقة باستخدام أحدث التقنيات الرقمية.","description_fr":"Conception et production de cartes géologiques et topographiques précises."},{"title_ar":"التحاليل المخبرية","title_fr":"Analyses en laboratoire","description_ar":"تحاليل متطورة للعينات المعدنية والصخرية باستخدام أحدث الأجهزة والتقنيات المخبرية.","description_fr":"Analyses avancées d''échantillons minéraux et rocheux."}]}'::jsonb WHERE page_id = v_pid AND sort_order = 3;

    UPDATE page_sections SET content = '{"_renderer":"partnerWhy","eyebrow_ar":"لماذا الشراكة معنا؟","eyebrow_fr":"Pourquoi un partenariat avec nous ?","heading_ar":"مميزات شراكتنا","heading_fr":"Les avantages de notre partenariat","description_ar":"نعمل جنبًا إلى جنب مع شركائنا لتحقيق النجاح المشترك.","description_fr":"Nous travaillons main dans la main avec nos partenaires.","cards":[{"title_ar":"خبرة مهنية","title_fr":"Expertise professionnelle","description_ar":"نمتلك خبرة تمتد لسنوات في مجال التنقيب والاستكشاف المعدني بالمغرب.","description_fr":"Nous possédons une expérience de plusieurs années."},{"title_ar":"شريك موثوق","title_fr":"Partenaire fiable","description_ar":"نلتزم بأعلى معايير الجودة والمهنية في جميع مشاريعنا وخدماتنا.","description_fr":"Nous respectons les plus hauts standards de qualité."},{"title_ar":"خدمات عالية الجودة","title_fr":"Services de haute qualité","description_ar":"نقدم خدمات متكاملة تلبي احتياجات شركائنا بأعلى مستوى من الدقة والكفاءة.","description_fr":"Nous offrons des services complets avec le plus haut niveau de précision."},{"title_ar":"تعاون وطني ودولي","title_fr":"Coopération nationale et internationale","description_ar":"نعمل في إطار تعاون وطني ودولي لتعزيز البحث والاستكشاف المعدني.","description_fr":"Nous travaillons en coopération nationale et internationale."}]}'::jsonb WHERE page_id = v_pid AND sort_order = 4;

    UPDATE page_sections SET content = '{"_renderer":"partnerGallery","eyebrow_ar":"معرض الصور","eyebrow_fr":"Galerie photos","heading_ar":"صور من أعمالنا","heading_fr":"Photos de nos travaux","description_ar":"جانب من أنشطتنا ومشاريعنا المشتركة.","description_fr":"Un aperçu de nos activités et projets communs.","images":[{"id":"gimg-0","url":"","alt":""},{"id":"gimg-1","url":"","alt":""},{"id":"gimg-2","url":"","alt":""},{"id":"gimg-3","url":"","alt":""},{"id":"gimg-4","url":"","alt":""},{"id":"gimg-5","url":"","alt":""}]}'::jsonb WHERE page_id = v_pid AND sort_order = 5;

    UPDATE page_sections SET content = '{"_renderer":"partnerContact","heading_ar":"تواصل معنا","heading_fr":"Contactez-nous","description_ar":"نحن هنا للإجابة على استفساراتكم.","description_fr":"Nous sommes là pour répondre à vos questions.","email":"contact@ancpp.ma","phone":"+212 528 000 000","website":"www.ancpp.ma","address":"ميناء أكادير، أكادير، المغرب"}'::jsonb WHERE page_id = v_pid AND sort_order = 6;

    UPDATE page_sections SET content = '{"_renderer":"partnerForm","heading_ar":"تواصل مع ANCPP","heading_fr":"Contacter ANCPP","description_ar":"أرسل لنا استفسارك وسنرد عليك في أقرب وقت.","description_fr":"Envoyez-nous votre demande et nous vous répondrons dans les plus brefs délais."}'::jsonb WHERE page_id = v_pid AND sort_order = 7;

    UPDATE page_sections SET content = '{"_renderer":"partnerCta","heading_ar":"هل أنت مهتم بالعمل مع هذا الشريك؟","heading_fr":"Intéressé par un partenariat ?","description":"","buttons":[{"id":"btn-pr-cta-0","label_ar":"زيارة الموقع الإلكتروني","label_fr":"Visiter le site web","url":"#","variant":"primary"},{"id":"btn-pr-cta-1","label_ar":"تواصل مع الشريك","label_fr":"Contacter le partenaire","url":"#prForm","variant":"secondary"}]}'::jsonb WHERE page_id = v_pid AND sort_order = 8;

    RAISE NOTICE 'ANCPP: sections updated.';
  END IF;

  -- #################################################################
  -- 5. OMSDS  (/partners/omsds)
  -- #################################################################
  SELECT id INTO v_pid FROM pages WHERE slug = '/partners/omsds' LIMIT 1;
  IF v_pid IS NOT NULL THEN

    UPDATE page_sections SET content = '{"heading_ar":"OMSDS","heading_fr":"OMSDS","subheading_ar":"شريك رئيسي","subheading_fr":"Partenaire principal","description_ar":"شريك رئيسي للجمعية المغربية لهواة البحث والاستكشاف، متخصص في مجال التنمية المستدامة والمبادرات البيئية بالمغرب.","description_fr":"Partenaire principal de l''Association Marocaine des Amateurs de Recherche et d''Exploration, spécialisé dans le développement durable et les initiatives environnementales au Maroc.","backgroundImage":"","buttons":[{"id":"btn-pr-website","label_ar":"زيارة الموقع الإلكتروني","label_fr":"Visiter le site web","url":"#","variant":"primary"},{"id":"btn-pr-contact","label_ar":"تواصل مع الشريك","label_fr":"Contacter le partenaire","url":"#prForm","variant":"secondary"}]}'::jsonb WHERE page_id = v_pid AND sort_order = 1;

    UPDATE page_sections SET content = '{"_renderer":"partnerAbout","eyebrow_ar":"عن OMSDS","eyebrow_fr":"À propos d''OMSDS","heading_ar":"شريككم الموثوق في مجال التنقيب والاستكشاف","heading_fr":"Votre partenaire de confiance","paragraphs_ar":["المنظمة المغربية للتنمية المستدامة هي منظمة وطنية تعمل على تعزيز التنمية المستدامة وحماية البيئة في المغرب.","نعمل مع الجمعية المغربية لهواة البحث والاستكشاف في إطار شراكة وطنية تهدف إلى تعزيز الوعي البيئي والاستدامة."],"paragraphs_fr":["L''Organisation Marocaine pour le Développement Durable est une organisation nationale œuvrant pour la promotion du développement durable et la protection de l''environnement au Maroc.","Nous travaillons avec l''Association Marocaine des Amateurs de Recherche et d''Exploration dans le cadre d''un partenariat national visant à renforcer la conscience environnementale et la durabilité."],"image":""}'::jsonb WHERE page_id = v_pid AND sort_order = 2;

    -- shared services / why / gallery
    UPDATE page_sections SET content = '{"_renderer":"partnerServices","eyebrow_ar":"خدماتنا","eyebrow_fr":"Nos services","heading_ar":"ماذا نقدم؟","heading_fr":"Que proposons-nous ?","description_ar":"نقدم مجموعة متكاملة من الخدمات المتخصصة في مجال التنقيب والاستكشاف.","description_fr":"Nous offrons une gamme complète de services spécialisés en prospection et exploration.","cards":[{"title_ar":"التنقيب المعدني","title_fr":"Prospection minière","description_ar":"دراسات جيولوجية متقدمة للتنقيب عن المعادن والثروات الطبيعية في مختلف مناطق المغرب.","description_fr":"Études géologiques avancées pour la prospection des minéraux."},{"title_ar":"الدراسات الجيولوجية","title_fr":"Études géologiques","description_ar":"تحليل وتوثيق التكوينات الجيولوجية وتقديم استشارات متخصصة للمشاريع الاستكشافية.","description_fr":"Analyse et documentation des formations géologiques."},{"title_ar":"رسم الخرائط","title_fr":"Cartographie","description_ar":"تصميم وإنتاج خرائط جيولوجية وطبوغرافية دقيقة باستخدام أحدث التقنيات الرقمية.","description_fr":"Conception et production de cartes géologiques et topographiques."},{"title_ar":"التحاليل المخبرية","title_fr":"Analyses en laboratoire","description_ar":"تحاليل متطورة للعينات المعدنية والصخرية باستخدام أحدث الأجهزة والتقنيات المخبرية.","description_fr":"Analyses avancées d''échantillons minéraux et rocheux."}]}'::jsonb WHERE page_id = v_pid AND sort_order = 3;

    UPDATE page_sections SET content = '{"_renderer":"partnerWhy","eyebrow_ar":"لماذا الشراكة معنا؟","eyebrow_fr":"Pourquoi un partenariat avec nous ?","heading_ar":"مميزات شراكتنا","heading_fr":"Les avantages de notre partenariat","description_ar":"نعمل جنبًا إلى جنب مع شركائنا لتحقيق النجاح المشترك.","description_fr":"Nous travaillons main dans la main avec nos partenaires.","cards":[{"title_ar":"خبرة مهنية","title_fr":"Expertise professionnelle","description_ar":"نمتلك خبرة تمتد لسنوات في مجال التنقيب والاستكشاف المعدني بالمغرب.","description_fr":"Nous possédons une expérience de plusieurs années."},{"title_ar":"شريك موثوق","title_fr":"Partenaire fiable","description_ar":"نلتزم بأعلى معايير الجودة والمهنية في جميع مشاريعنا وخدماتنا.","description_fr":"Nous respectons les plus hauts standards de qualité."},{"title_ar":"خدمات عالية الجودة","title_fr":"Services de haute qualité","description_ar":"نقدم خدمات متكاملة تلبي احتياجات شركائنا بأعلى مستوى من الدقة والكفاءة.","description_fr":"Nous offrons des services complets avec le plus haut niveau de précision."},{"title_ar":"تعاون وطني ودولي","title_fr":"Coopération nationale et internationale","description_ar":"نعمل في إطار تعاون وطني ودولي لتعزيز البحث والاستكشاف المعدني.","description_fr":"Nous travaillons en coopération nationale et internationale."}]}'::jsonb WHERE page_id = v_pid AND sort_order = 4;

    UPDATE page_sections SET content = '{"_renderer":"partnerGallery","eyebrow_ar":"معرض الصور","eyebrow_fr":"Galerie photos","heading_ar":"صور من أعمالنا","heading_fr":"Photos de nos travaux","description_ar":"جانب من أنشطتنا ومشاريعنا المشتركة.","description_fr":"Un aperçu de nos activités et projets communs.","images":[{"id":"gimg-0","url":"","alt":""},{"id":"gimg-1","url":"","alt":""},{"id":"gimg-2","url":"","alt":""},{"id":"gimg-3","url":"","alt":""},{"id":"gimg-4","url":"","alt":""},{"id":"gimg-5","url":"","alt":""}]}'::jsonb WHERE page_id = v_pid AND sort_order = 5;

    UPDATE page_sections SET content = '{"_renderer":"partnerContact","heading_ar":"تواصل معنا","heading_fr":"Contactez-nous","description_ar":"نحن هنا للإجابة على استفساراتكم.","description_fr":"Nous sommes là pour répondre à vos questions.","email":"contact@omsds.org","phone":"+212 537 000 000","website":"www.omsds.org","address":"شارع محمد السادس، مراكش، المغرب"}'::jsonb WHERE page_id = v_pid AND sort_order = 6;

    UPDATE page_sections SET content = '{"_renderer":"partnerForm","heading_ar":"تواصل مع OMSDS","heading_fr":"Contacter OMSDS","description_ar":"أرسل لنا استفسارك وسنرد عليك في أقرب وقت.","description_fr":"Envoyez-nous votre demande et nous vous répondrons dans les plus brefs délais."}'::jsonb WHERE page_id = v_pid AND sort_order = 7;

    UPDATE page_sections SET content = '{"_renderer":"partnerCta","heading_ar":"هل أنت مهتم بالعمل مع هذا الشريك؟","heading_fr":"Intéressé par un partenariat ?","description":"","buttons":[{"id":"btn-pr-cta-0","label_ar":"زيارة الموقع الإلكتروني","label_fr":"Visiter le site web","url":"#","variant":"primary"},{"id":"btn-pr-cta-1","label_ar":"تواصل مع الشريك","label_fr":"Contacter le partenaire","url":"#prForm","variant":"secondary"}]}'::jsonb WHERE page_id = v_pid AND sort_order = 8;

    RAISE NOTICE 'OMSDS: sections updated.';
  END IF;

  -- #################################################################
  -- 6. Association Detection Centre  (/partners/detection-centre)
  -- #################################################################
  SELECT id INTO v_pid FROM pages WHERE slug = '/partners/detection-centre' LIMIT 1;
  IF v_pid IS NOT NULL THEN

    UPDATE page_sections SET content = '{"heading_ar":"مركز الكشف والاستكشاف","heading_fr":"Centre de Détection et d''Exploration","subheading_ar":"شريك استراتيجي","subheading_fr":"Partenaire stratégique","description_ar":"شريك استراتيجي للجمعية المغربية لهواة البحث والاستكشاف، متخصص في التدريب والتكوين في مجال أجهزة الكشف والتنقيب.","description_fr":"Partenaire stratégique de l''Association Marocaine des Amateurs de Recherche et d''Exploration, spécialisé dans la formation aux détecteurs et à la prospection.","backgroundImage":"","buttons":[{"id":"btn-pr-website","label_ar":"زيارة الموقع الإلكتروني","label_fr":"Visiter le site web","url":"#","variant":"primary"},{"id":"btn-pr-contact","label_ar":"تواصل مع الشريك","label_fr":"Contacter le partenaire","url":"#prForm","variant":"secondary"}]}'::jsonb WHERE page_id = v_pid AND sort_order = 1;

    UPDATE page_sections SET content = '{"_renderer":"partnerAbout","eyebrow_ar":"عن مركز الكشف والاستكشاف","eyebrow_fr":"À propos du Centre de Détection","heading_ar":"شريككم الموثوق في مجال التنقيب والاستكشاف","heading_fr":"Votre partenaire de confiance","paragraphs_ar":["مركز الكشف والاستكشاف هو مؤسسة متخصصة في التدريب والتكوين على استخدام أجهزة الكشف عن المعادن والتنقيب عن الكنوز.","نعمل مع الجمعية المغربية لهواة البحث والاستكشاف في إطار شراكة استراتيجية تهدف إلى تطوير مهارات الأعضاء في مجال الكشف والتنقيب."],"paragraphs_fr":["Le Centre de Détection et d''Exploration est une institution spécialisée dans la formation à l''utilisation des détecteurs de métaux et à la prospection.","Nous travaillons avec l''Association Marocaine des Amateurs de Recherche et d''Exploration dans le cadre d''un partenariat stratégique visant à développer les compétences des membres en détection et prospection."],"image":""}'::jsonb WHERE page_id = v_pid AND sort_order = 2;

    -- shared services / why / gallery
    UPDATE page_sections SET content = '{"_renderer":"partnerServices","eyebrow_ar":"خدماتنا","eyebrow_fr":"Nos services","heading_ar":"ماذا نقدم؟","heading_fr":"Que proposons-nous ?","description_ar":"نقدم مجموعة متكاملة من الخدمات المتخصصة في مجال التنقيب والاستكشاف.","description_fr":"Nous offrons une gamme complète de services spécialisés.","cards":[{"title_ar":"التنقيب المعدني","title_fr":"Prospection minière","description_ar":"دراسات جيولوجية متقدمة للتنقيب عن المعادن والثروات الطبيعية.","description_fr":"Études géologiques avancées pour la prospection des minéraux."},{"title_ar":"الدراسات الجيولوجية","title_fr":"Études géologiques","description_ar":"تحليل وتوثيق التكوينات الجيولوجية وتقديم استشارات متخصصة.","description_fr":"Analyse et documentation des formations géologiques."},{"title_ar":"رسم الخرائط","title_fr":"Cartographie","description_ar":"تصميم وإنتاج خرائط جيولوجية وطبوغرافية دقيقة.","description_fr":"Conception et production de cartes géologiques et topographiques."},{"title_ar":"التحاليل المخبرية","title_fr":"Analyses en laboratoire","description_ar":"تحاليل متطورة للعينات المعدنية والصخرية.","description_fr":"Analyses avancées d''échantillons minéraux et rocheux."}]}'::jsonb WHERE page_id = v_pid AND sort_order = 3;

    UPDATE page_sections SET content = '{"_renderer":"partnerWhy","eyebrow_ar":"لماذا الشراكة معنا؟","eyebrow_fr":"Pourquoi un partenariat avec nous ?","heading_ar":"مميزات شراكتنا","heading_fr":"Les avantages de notre partenariat","description_ar":"نعمل جنبًا إلى جنب مع شركائنا لتحقيق النجاح المشترك.","description_fr":"Nous travaillons main dans la main avec nos partenaires.","cards":[{"title_ar":"خبرة مهنية","title_fr":"Expertise professionnelle","description_ar":"نمتلك خبرة تمتد لسنوات في مجال التنقيب والاستكشاف المعدني.","description_fr":"Nous possédons une expérience de plusieurs années."},{"title_ar":"شريك موثوق","title_fr":"Partenaire fiable","description_ar":"نلتزم بأعلى معايير الجودة والمهنية.","description_fr":"Nous respectons les plus hauts standards de qualité."},{"title_ar":"خدمات عالية الجودة","title_fr":"Services de haute qualité","description_ar":"نقدم خدمات متكاملة بأعلى مستوى من الدقة.","description_fr":"Nous offrons des services complets avec le plus haut niveau de précision."},{"title_ar":"تعاون وطني ودولي","title_fr":"Coopération nationale et internationale","description_ar":"نعمل في إطار تعاون وطني ودولي.","description_fr":"Nous travaillons en coopération nationale et internationale."}]}'::jsonb WHERE page_id = v_pid AND sort_order = 4;

    UPDATE page_sections SET content = '{"_renderer":"partnerGallery","eyebrow_ar":"معرض الصور","eyebrow_fr":"Galerie photos","heading_ar":"صور من أعمالنا","heading_fr":"Photos de nos travaux","description_ar":"جانب من أنشطتنا ومشاريعنا المشتركة.","description_fr":"Un aperçu de nos activités et projets communs.","images":[{"id":"gimg-0","url":"","alt":""},{"id":"gimg-1","url":"","alt":""},{"id":"gimg-2","url":"","alt":""},{"id":"gimg-3","url":"","alt":""},{"id":"gimg-4","url":"","alt":""},{"id":"gimg-5","url":"","alt":""}]}'::jsonb WHERE page_id = v_pid AND sort_order = 5;

    UPDATE page_sections SET content = '{"_renderer":"partnerContact","heading_ar":"تواصل معنا","heading_fr":"Contactez-nous","description_ar":"نحن هنا للإجابة على استفساراتكم.","description_fr":"Nous sommes là pour répondre à vos questions.","email":"contact@detection-centre.ma","phone":"+212 539 000 000","website":"www.detection-centre.ma","address":"شارع فلسطين، طنجة، المغرب"}'::jsonb WHERE page_id = v_pid AND sort_order = 6;

    UPDATE page_sections SET content = '{"_renderer":"partnerForm","heading_ar":"تواصل مع مركز الكشف","heading_fr":"Contacter le Centre de Détection","description_ar":"أرسل لنا استفسارك وسنرد عليك في أقرب وقت.","description_fr":"Envoyez-nous votre demande et nous vous répondrons dans les plus brefs délais."}'::jsonb WHERE page_id = v_pid AND sort_order = 7;

    UPDATE page_sections SET content = '{"_renderer":"partnerCta","heading_ar":"هل أنت مهتم بالعمل مع هذا الشريك؟","heading_fr":"Intéressé par un partenariat ?","description":"","buttons":[{"id":"btn-pr-cta-0","label_ar":"زيارة الموقع الإلكتروني","label_fr":"Visiter le site web","url":"#","variant":"primary"},{"id":"btn-pr-cta-1","label_ar":"تواصل مع الشريك","label_fr":"Contacter le partenaire","url":"#prForm","variant":"secondary"}]}'::jsonb WHERE page_id = v_pid AND sort_order = 8;

    RAISE NOTICE 'AssocDetectionCentre: sections updated.';
  END IF;

  RAISE NOTICE '=========================================';
  RAISE NOTICE '  ALL 6 partner pages migrated to bilingual _ar/_fr.';
  RAISE NOTICE '=========================================';
END $$;
