/**
 * Page Discovery Service
 *
 * Auto-discovers every public website page from the project HTML files.
 * Reusable – call `getWebsitePages()` anywhere to get the full page list.
 *
 * Ignored pages:
 *   - Dashboard / Admin pages
 *   - Login
 *   - Members
 *   - News dashboard
 *   - Updates dashboard
 *   - Store dashboard
 *   - Control Panel
 *   - Content Editor
 *   - Preview utility
 *
 * When a new HTML page is added to the website, add it to the manifest below
 * and it immediately appears in the Content Editor sidebar.
 */

export interface DiscoveredPage {
  /** Unique identifier (derived from filename) */
  id: string
  /** Display name extracted from the HTML <title> tag */
  name: string
  /** Public URL path relative to the site root */
  path: string
  /** Navigation section the page belongs to */
  section: string
  /** Sort order matching the website navigation */
  order: number
}

/**
 * Auto-assigns a Lucide icon name to each page based on its path/section.
 * Icons are determined programmatically, not hardcoded per page.
 */
function assignIcon(page: DiscoveredPage): string {
  const path = page.path.toLowerCase()
  const name = page.name.toLowerCase()
  const section = page.section.toLowerCase()

  if (page.id === 'home') return 'home'
  if (section.includes('نبذة') || section.includes('about') || page.id === 'central-office')
    return 'building2'
  if (name.includes('رؤي') || name.includes('vision')) return 'eye'
  if (name.includes('رسال') || name.includes('mission')) return 'target'
  if (name.includes('قيم') || name.includes('values')) return 'heart'
  if (name.includes('خرائط') || name.includes('توسع') || name.includes('expansion'))
    return 'map'
  if (section.includes('فرع') || section.includes('branch') || path.includes('regional-branches'))
    return 'map-pinned'
  if (
    name.includes('انخراط') ||
    name.includes('join') ||
    name.includes('register') ||
    name.includes('تسجيل')
  )
    return 'user-plus'
  if (name.includes('تجديد') || name.includes('renewal')) return 'refresh-cw'
  if (name.includes('وثائ') || name.includes('document')) return 'files'
  if (name.includes('قانون') || name.includes('bylaw') || name.includes('regulation'))
    return 'book-open'
  if (name.includes('ميثاق') || name.includes('charter')) return 'scroll'
  if (name.includes('إيداع') || name.includes('deposit')) return 'folder-open'
  if (name.includes('إشعار') || name.includes('notification') || name.includes('خرجات'))
    return 'bell'
  if (name.includes('استمار') || name.includes('application')) return 'clipboard-list'
  if (name.includes('التزا') || name.includes('commitment')) return 'file-check'
  if (name.includes('اتصل') || name.includes('contact') || name.includes('تواصل')) return 'mail'
  return 'file-text'
}

// ---------------------------------------------------------------------------
// Discovered pages manifest
// Generated by scanning the project root for public HTML files.
// Run `node dashboard/scripts/discover-pages.js` to regenerate.
// ---------------------------------------------------------------------------

const MANIFEST: DiscoveredPage[] = [
  {
    id: 'home',
    name: 'الرئيسية',
    path: '/',
    section: 'الرئيسية',
    order: 1,
  },
  {
    id: 'about',
    name: 'من نحن',
    path: '/about',
    section: 'من نحن',
    order: 2,
  },
  {
    id: 'our-activities',
    name: 'أنشطتنا',
    path: '/activities',
    section: 'أنشطتنا',
    order: 3,
  },
  {
    id: 'partners-lefouilleurma',
    name: 'Le Fouilleur',
    path: '/partners/lefouilleurma',
    section: 'شركاؤنا',
    order: 4,
  },
  {
    id: 'partners-senotec',
    name: 'SENOTEC',
    path: '/partners/senotec',
    section: 'شركاؤنا',
    order: 5,
  },
  {
    id: 'partners-astromet',
    name: 'ASTROMET',
    path: '/partners/astromet',
    section: 'شركاؤنا',
    order: 6,
  },
  {
    id: 'partners-detection-centre',
    name: 'Association Detection Centre',
    path: '/partners/detection-centre',
    section: 'شركاؤنا',
    order: 7,
  },
  {
    id: 'partners-ancpp',
    name: 'ANCPP',
    path: '/partners/ancpp',
    section: 'شركاؤنا',
    order: 8,
  },
  {
    id: 'partners-omsds',
    name: 'OMSDS',
    path: '/partners/omsds',
    section: 'شركاؤنا',
    order: 9,
  },
  {
    id: 'rabat-sale-kenitra',
    name: 'جهة الرباط - سلا - القنيطرة',
    path: '/regional-branches/rabat-sale-kenitra.html',
    section: 'الفروع الجهوية',
    order: 7,
  },
  {
    id: 'tanger-tetouan-al-hoceima',
    name: 'جهة طنجة - تطوان - الحسيمة',
    path: '/regional-branches/tanger-tetouan-al-hoceima.html',
    section: 'الفروع الجهوية',
    order: 8,
  },
  {
    id: 'join-us-online',
    name: 'الانخراط عبر الإنترنت',
    path: '/Join%20us/join-us-online.html',
    section: 'انخرط معنا',
    order: 9,
  },
  {
    id: 'membership-renewal',
    name: 'تجديد الانخراط',
    path: '/Join%20us/membership-renewal.html',
    section: 'انخرط معنا',
    order: 10,
  },
  {
    id: 'documents',
    name: 'وثائق الانخراط',
    path: '/Join%20us/documents.html',
    section: 'انخرط معنا',
    order: 11,
  },
  {
    id: 'contact',
    name: 'اتصل بنا',
    path: '/contact.html',
    section: 'اتصل بنا',
    order: 20,
  },
]

export interface ResolvedPage extends DiscoveredPage {
  icon: string
}

// ---------------------------------------------------------------------------
// Public API
// ---------------------------------------------------------------------------

/** Returns all discovered website pages, ordered by navigation position. */
export function getWebsitePages(): ResolvedPage[] {
  return [...MANIFEST]
    .sort((a, b) => a.order - b.order)
    .map((page) => ({ ...page, icon: assignIcon(page) }))
}

/** Finds a single page by its id. */
export function getPageById(id: string): ResolvedPage | undefined {
  return getWebsitePages().find((page) => page.id === id)
}

/** Finds pages whose path matches a given search term. */
export function searchPages(query: string): ResolvedPage[] {
  const trimmed = query.trim().toLowerCase()
  if (!trimmed) return getWebsitePages()
  return getWebsitePages().filter(
    (page) =>
      page.name.toLowerCase().includes(trimmed) ||
      page.section.toLowerCase().includes(trimmed) ||
      page.path.toLowerCase().includes(trimmed),
  )
}

/** Returns unique section names in navigation order. */
export function getSections(): string[] {
  const pages = getWebsitePages()
  const seen: Record<string, boolean> = {}
  const result: string[] = []
  for (const page of pages) {
    if (!seen[page.section]) {
      seen[page.section] = true
      result.push(page.section)
    }
  }
  return result
}
